Check if files exist before sourcing them

diff --git a/src/bin/adsorber b/src/bin/adsorber
--- a/src/bin/adsorber
+++ b/src/bin/adsorber
@@ -71,7 +71,7 @@ showUsage()
         fi
 
         echo "Usage: adsorber <install|update|restore|revert|remove> [<options>]"
-        echo "Try --help for more information."
+        echo "Try '--help' for more information."
 
         exit 80
 }
@@ -119,7 +119,7 @@ showSpecificHelp()
 {
         case "${operation}" in
                 install )
-                        printf "%badsorber install [<options>]%b:\\n" "${prefix_underline}" "${prefix_reset}"
+                        printf "\\033[4;37madsorber install [<options>]\\033[0m:\\n"
                         echo
                         echo "You should run this command first."
                         echo
@@ -138,7 +138,7 @@ showSpecificHelp()
                         echo " -h,  --help               - show this help screen"
                         ;;
                 update )
-                        printf "%badsorber update [<options>]%b:\\n" "${prefix_underline}" "${prefix_reset}"
+                        printf "\\033[4;37madsorber update [<options>]\\033[0m:\\n"
                         echo
                         echo "To keep the hosts file up-to-date."
                         echo
@@ -151,7 +151,7 @@ showSpecificHelp()
                         echo " -h, --help       - show this help screen"
                         ;;
                 restore )
-                        printf "%badsorber restore [<options>]%b:\\n" "${prefix_underline}" "${prefix_reset}"
+                        printf "\\033[4;37madsorber restore [<options>]\\033[0m:\\n"
                         echo
                         echo "To restore the hosts file temporary, without removing the backup."
                         echo
@@ -169,7 +169,7 @@ showSpecificHelp()
                         echo " -h, --help       - show this help screen"
                         ;;
                 revert )
-                        printf "%badsorber revert [<options>]%b:\\n" "${prefix_underline}" "${prefix_reset}"
+                        printf "\\033[4;37madsorber revert [<options>]\\033[0m:\\n"
                         echo
                         echo "To revert to the last hosts file, good use if the"
                         echo "current host file was corrupted."
@@ -183,14 +183,14 @@ showSpecificHelp()
                         echo " -h, --help       - show this help screen"
                         ;;
                 remove )
-                        printf "%badsorber remove [<options>]%b:\\n" "${prefix_underline}" "${prefix_reset}"
+                        printf "\\033[4;37madsorber remove [<options>]\\033[0m:\\n"
                         echo
                         echo "To completely remove changes made by Adsorber."
                         echo
                         echo "The command will:"
                         echo " - remove all schedulers (systemd, cronjob)"
                         echo " - restore the hosts file to it's original state"
-                        echo " - remove all leftovers"
+                        echo " - remove all leftovers (e.g. /tmp/adsorber)"
                         echo
                         echo "Possible options:"
                         echo " -y, --yes, --assume-yes  - answer all prompts with 'yes'"
@@ -235,6 +235,37 @@ duplicateOption()
 }
 
 
+checkPaths()
+{
+        # Check if essential files for adsorber exists, if not, try to fix or abort
+
+        _not_found=false
+
+        if [ ! -e "${library_dir_path}" ]; then
+                printf "\\033[0;91mE Invalid library_dir_path, can't access %s\\033[0m\\n" "${library_dir_path}"
+                _not_found=true
+        fi
+
+        if [ ! -e "${config_dir_path}" ]; then
+                mkdir -p "${config_dir_path}"
+        fi
+
+        if [ ! -e "${shareable_dir_path}" ]; then
+                printf "\\033[0;91mE Invalid shareable_dir_path, can't access %s\\033[0m\\n" "${shareable_dir_path}"
+                _not_found=true
+        fi
+
+        if [ "${_not_found}" = "true" ]; then
+                echo "  To fix: completely remove Adsorber from the system and re-install it again."
+                echo "  Please fix the problem(s) and try again."
+                exit 1
+        fi
+
+        unset _not_found
+
+        return 0
+}
+
 
 sourceFiles()
 {
@@ -253,7 +284,7 @@ sourceFiles()
         # shellcheck source=../src/lib/colours.sh
         . "${library_dir_path}/colours.sh"
 
-        # Only source when needed?
+        # Maybe source them only when needed?
         # shellcheck source=../src/lib/cron/cron.sh
         . "${library_dir_path}/cron/cron.sh"
         # shellcheck source=../src/lib/systemd/systemd.sh
@@ -262,7 +293,7 @@ sourceFiles()
         return 0
 }
 
-
+checkPaths
 sourceFiles
 
 for _option in "${@}"; do
@@ -363,6 +394,6 @@ case "${operation}" in
                 ;;
 esac
 
-printf "%bFinished successfully.%b\\n" "${prefix_title}" "${prefix_reset}"
+printf "\\033[1;37mFinished successfully.\\033[0m\\n"
 
 exit 0
