Introduced naming convention for variables

diff --git a/src/bin/adsorber b/src/bin/adsorber
--- a/src/bin/adsorber
+++ b/src/bin/adsorber
@@ -4,6 +4,10 @@
 # Repository: https://github.com/stablestud/adsorber
 # License:    MIT, https://opensource.org/licenses/MIT
 
+# Variable naming:
+# under_score        - used for global variables which are accessible between functions.
+# _extra_under_score - used for local function variables. Should be unset afterwards.
+#          (Note the underscore in the beginning of _extra_under_score!)
 
 readonly tmp_dir_path="/tmp/adsorber"
 
@@ -12,17 +16,17 @@ readonly executable_dir_path="$(cd "$(dirname "${0}")" && pwd)"
 readonly library_dir_path="${executable_dir_path}/../lib"
 readonly shareable_dir_path="${executable_dir_path}/../share"
 readonly config_dir_path="${executable_dir_path}/../.."
-#############################################################################
+################################################################################
 
 readonly version="0.4.0"
 
-readonly operation="${1}"
+readonly _operation="${1}"
 
 if [ "${#}" -ne 0 ]; then
         shift
 fi
 
-readonly options="${*}"
+readonly _options="${*}"
 
 checkRoot()
 {
@@ -37,11 +41,11 @@ checkRoot()
 
 checkForWrongParameters()
 {
-        if [ -n "${wrong_operation}" ] || [ -n "${wrong_option}" ]; then
+        if [ -n "${_wrong_operation}" ] || [ -n "${_wrong_option}" ]; then
                 showUsage
         fi
 
-        if [ "${option_help}" = "true"  ]; then
+        if [ "${_option_help}" = "true"  ]; then
                 showSpecificHelp
         fi
 
@@ -51,12 +55,12 @@ checkForWrongParameters()
 
 showUsage()
 {
-        if [ -n "${wrong_operation}" ]; then
-                echo "Adsorber: Invalid operation: '${wrong_operation}'" 1>&2
+        if [ -n "${_wrong_operation}" ]; then
+                echo "Adsorber: Invalid operation: '${_wrong_operation}'" 1>&2
         fi
 
-        if [ -n "${wrong_option}" ]; then
-                echo "Adsorber: Invalid option: '${wrong_option}'" 1>&2
+        if [ -n "${_wrong_option}" ]; then
+                echo "Adsorber: Invalid option: '${_wrong_option}'" 1>&2
         fi
 
         echo "Usage: adsorber <install|update|restore|revert|remove> [<options>]"
@@ -106,7 +110,7 @@ showHelp()
 
 showSpecificHelp()
 {
-        case "${operation}" in
+        case "${_operation}" in
                 install )
                         printf "%badsorber install [<options>]%b:\n" "${uwhite}" "${prefix_reset}"
                         echo
@@ -210,13 +214,13 @@ showVersion()
 duplicateOption()
 {
         if [ "${1}" = "scheduler" ]; then
-                echo "Adsorber: Duplicate option for scheduler: '${option}'" 1>&2
+                echo "Adsorber: Duplicate option for scheduler: '${_option}'" 1>&2
                 echo "You may only select one:"
                 echo "  -s,  --systemd           - use Systemd ..."
                 echo "  -c,  --cron              - use Cronjob as scheduler (use with 'install')"
                 echo "  -ns, --no-scheduler      - skip scheduler creation (use with 'install')"
         else
-                echo "Adsorber: Duplicate option: '${option}'" 1>&2
+                echo "Adsorber: Duplicate option: '${_option}'" 1>&2
                 showUsage
         fi
 
@@ -241,9 +245,9 @@ sourceFiles()
 
 sourceFiles
 
-for option in "${@}"; do
+for _option in "${@}"; do
 
-        case "${option}" in
+        case "${_option}" in
                 -[Ss] | --systemd )
                         readonly reply_to_scheduler_prompt="systemd" 2>/dev/null || duplicateOption "scheduler"
                         ;;
@@ -263,16 +267,16 @@ for option in "${@}"; do
                         : # Do nothing
                         ;;
                 -[Hh] | --help | help )
-                        readonly option_help="true" 2>/dev/null
+                        readonly _option_help="true" 2>/dev/null
                         ;;
                 * )
-                        wrong_option="${option}" 2>/dev/null
+                        _wrong_option="${_option}" 2>/dev/null
                         ;;
         esac
 
 done
 
-case "${operation}" in
+case "${_operation}" in
         install )
                 checkForWrongParameters
                 checkRoot
@@ -314,7 +318,7 @@ case "${operation}" in
                 showUsage
                 ;;
         * )
-                readonly wrong_operation="${operation}"
+                readonly _wrong_operation="${_operation}"
                 showUsage
                 ;;
 esac
